spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/travel_app_db
spring.datasource.username=travel_user
spring.datasource.password=travel_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:dev-secret-change-me}
app.jwt.expiration-ms=86400000
pexels.api.key=${PEXELS_API_KEY:}
weather.api.key=${WEATHER_API_KEY:}
currency.api.key=${CURRENCY_API_KEY:}