spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/travel_app_db
spring.datasource.username=travel_user
spring.datasource.password=travel_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=VGhpcy1pcy1hLWRldi1qd3Qtc2VjcmV0LWZvci10cmF2ZWwtYXBwLTIwMjY=
app.jwt.expiration-ms=86400000